SELECT 
    CASE 
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 0 AND 1 THEN '0-1 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 2 AND 7 THEN '2-7 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 8 AND 30 THEN '8-30 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 31 AND 90 THEN '31-90 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) > 90 THEN '>90 Days'
        ELSE 'Unknown'
    END AS Time_To_Event_Range,
    COUNT(*) AS Event_Count
FROM vdata vd
join vax vx on vx.vaers_id = vd.vaers_id
WHERE
vx.vax_type like 'COVID%'
and YEAR(vax_date) >= 2020
and VAX_DATE IS NOT NULL 
    AND ONSET_DATE IS NOT NULL
    AND DATEDIFF(DAY, VAX_DATE, ONSET_DATE) >= 0
GROUP BY 
    CASE 
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 0 AND 1 THEN '0-1 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 2 AND 7 THEN '2-7 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 8 AND 30 THEN '8-30 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) BETWEEN 31 AND 90 THEN '31-90 Days'
        WHEN DATEDIFF(DAY, VAX_DATE, ONSET_DATE) > 90 THEN '>90 Days'
        ELSE 'Unknown'
    END
ORDER BY Event_Count DESC;